@startuml 1_kullanim_durumu
!include _stil.iuml
title Kullanım durumu diyagramı
left to right direction
skinparam actorStyle hollow

rectangle "Ziyaretçi" as Z <<aktör>>
rectangle "Üye" as U <<aktör>>
rectangle "Yönetici" as Y <<aktör>>

rectangle Agora {
  usecase "Kayıt ol / giriş yap" as K
  usecase "Konu aç" as KA
  usecase "Mesaj yaz" as M
  usecase "Oy ver" as OY
  usecase "Şikayeti incele" as S
}

Z -- K
U -- KA
U -- M
U -- OY
Y -- S
@enduml
