@startuml 2_sinif
!include _stil.iuml
title Sınıf diyagramı

class Kullanici {
  takma_ad
  sifre
}
class Konu {
  baslik
  durum
}
class Mesaj {
  icerik
}
class Oylama {
  bitis
}
class Fikir {
  metin
}
class Oy {
  secim
}

Kullanici "1" -- "*" Konu : açar
Konu "1" -- "*" Mesaj : içerir
Konu "1" -- "*" Oylama
Oylama "1" -- "*" Fikir
Oylama "1" -- "*" Oy
Kullanici "1" -- "*" Oy : verir
@enduml
